[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.17"
via_ir = true           # Enable IR-based code generation
optimizer = true        # Enable the optimizer

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
fs_permissions = [{ access = "read", path = "./"}]
